services:
  app:
    image: autoctonos-web
    build:
      context: ./
      target: ${env}         
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: "http://localhost:3000"
      AUTH_SECRET: "qonr9OfFupelAk77EeShZH+GXSGlStoNev+e0XlNMmk="
      BACKEND_URL: "http://localhost:8000/api"   # nombre del contenedor backend en la MISMA red
      NEXT_PUBLIC_BACKEND: "http://localhost:8000/api"  # opcional si sigues llamando directo desde el browser
      PAYU_MERCHANT_ID: "508029"
      PAYU_ACCOUNT_ID: "512321"
      PAYU_API_KEY: "4Vj8eK4rloUd272L48hsrarnUA"
    ports:
      - "3000:3000"
    networks:
      - autoctonos_network

networks:
  autoctonos_network:
    external: true
