version: '3.8'
services:
  app:
    image: autoctonos-web
    build:
      context: ./
      target: ${env}
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000" 